### ISSUE TITLE
Add support for beta versions like godot 4.3 betas and rc versions?

### ISSUE THREAD

**Issue by michaelwschultz** [dulvui/godot-4-html-export#3]
Any chance this could be supported easily? Also, version 2 of the extension doesn't seem to work right. I had to revert to version 1 or I get this error.

![image](https://github.com/user-attachments/assets/f7a81e42-b315-45a2-8247-009c5322be41)

**Comment by dulvui** [comment]
Yes this should be possible easily, in this action I'm still using the old URL https://downloads.tuxfamily.org/godotengine/ and haven't switched yet to https://github.com/godotengine/godot/releases/
Then then v4.3-rc3 should be working as godot-version parameter.

Should be fixed by the end of the day.

**Comment by dulvui** [comment]
@michaelwschultz I made some changes and added `godot-channel` action input, where the release channel, such as stable or rc3 can be defined.
It's still not working completely and needs some refactoring. I'll let you know when  it's working fine.

**Comment by dulvui** [comment]
Now it works!
You can find a working example of the action in use here https://github.com/dulvui/condor/blob/main/.github/workflows/upload-itchio.yml

**Comment by michaelwschultz** [comment]
No way!! Sorry I don't get back to ya. Thanks so much. I'll check it out tomorrow. In the middle of a jam now so this will be really helpful!

**Comment by michaelwschultz** [comment]
Btw I noticed you use to have caching then removed it. What were the issues you run into? Seems like it would be great to cache the Godot runtime download since it's close to a gig.

**Comment by dulvui** [comment]
You are welcome, I'm happy to help :-)

The cache should still be there and work. Here you can see the cache that was built during my test
https://github.com/dulvui/condor/actions/caches

I just added also the release channel to the cache's name, so on next build the name should be Linux-godot-4.3-rc3
